# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edff7325fb810a3e27b4cc5ef379c183741d92c6c16bcbe1a4a56465a220f615d8c319beb95bab1a68dd8b8e3134d29329b0ecf41353491708580a22349ebc20

test:
  secret_key_base: 58284ee009095c1c8b801d7e3193cf8a27be3ac6e62c501e8a1c5248e594ea1cae472ca46d9398a2e3fcab0af2bcaf067acbf1bd764a41e6bd124e1ae124acc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
